const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Keyboard,
		C3.Plugins.Browser,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Text,
		C3.Plugins.Sprite,
		C3.Behaviors.Sin,
		C3.Behaviors.MoveTo,
		C3.Plugins.Tilemap,
		C3.Behaviors.skymen_Skymen_SpritefontDX,
		C3.Plugins.Audio,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Plugins.System.Cnds.CompareBoolVar,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Exps.int,
		C3.Plugins.Tilemap.Exps.Width,
		C3.Plugins.Tilemap.Exps.TileWidth,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Behaviors.MoveTo.Acts.SetAcceleration,
		C3.Behaviors.MoveTo.Acts.SetDeceleration,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Tilemap.Exps.TileToPositionX,
		C3.Plugins.Tilemap.Exps.PositionToTileX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Tilemap.Exps.TileToPositionY,
		C3.Plugins.Tilemap.Exps.PositionToTileY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetTop,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetRight,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Acts.SetLayerScroll,
		C3.Plugins.Tilemap.Exps.Height,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Text.Acts.SetVisible,
		C3.Plugins.Text.Acts.SetText,
		C3.JavaScriptInEvents.Egame_Event29_Act4,
		C3.JavaScriptInEvents.Egame_Event33_Act2,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.JavaScriptInEvents.Egame_Event39_Act2,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Audio.Acts.SetMasterVolume,
		C3.JavaScriptInEvents.Egame_Event43_Act3,
		C3.Plugins.System.Cnds.Else,
		C3.JavaScriptInEvents.Egame_Event44_Act3,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.JavaScriptInEvents.Egame_Event58_Act7,
		C3.JavaScriptInEvents.Egame_Event58_Act8,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Cnds.LayerVisible,
		C3.Plugins.Sprite.Cnds.IsVisible,
		C3.Plugins.Keyboard.Cnds.OnKey,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Touch.Cnds.CompareTouchSpeed,
		C3.Plugins.Touch.Exps.AngleAt,
		C3.Plugins.System.Cnds.CompareBetween,
		C3.Behaviors.MoveTo.Cnds.IsMoving,
		C3.Plugins.System.Cnds.PickAll,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.System.Cnds.PickRandom,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Behaviors.MoveTo.Exps.MaxSpeed,
		C3.Behaviors.MoveTo.Exps.Acceleration,
		C3.Behaviors.MoveTo.Exps.Deceleration,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Tilemap.Exps.TileHeight,
		C3.Plugins.Sprite.Exps.UID,
		C3.Plugins.Sprite.Cnds.PickByUID,
		C3.Plugins.System.Cnds.PickOverlappingPoint,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.System.Cnds.PickByComparison,
		C3.Plugins.Sprite.Cnds.PickDistance,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Behaviors.MoveTo.Acts.MoveToObject,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrameCount,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Exps.max,
		C3.JavaScriptInEvents.Egame_Event136_Act2,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.System.Cnds.OnLayoutEnd
	];
};
self.C3_JsPropNameTable = [
	{Touch: 0},
	{LocalStorage: 0},
	{Keyboard: 0},
	{Browser: 0},
	{PlatformInfo: 0},
	{BaseText: 0},
	{txtBest: 0},
	{Sine: 0},
	{btnPlay: 0},
	{character: 0},
	{logo: 0},
	{BoardBest: 0},
	{BG1: 0},
	{Moving: 0},
	{MoveTo: 0},
	{Box: 0},
	{BoxNumber: 0},
	{Tilemap: 0},
	{Marker: 0},
	{Syncer: 0},
	{SuccsTXT: 0},
	{AnimateText: 0},
	{TimeAdded: 0},
	{btnPause: 0},
	{btnReplay: 0},
	{btnResume: 0},
	{txtHelp: 0},
	{txtScore: 0},
	{logo2: 0},
	{BG2: 0},
	{score: 0},
	{Timer: 0},
	{txtTimer: 0},
	{Label: 0},
	{btnHome: 0},
	{GoHomeBtn: 0},
	{MusicBtn: 0},
	{ExsitBtn: 0},
	{Audio: 0},
	{boy: 0},
	{DBG: 0},
	{soBad: 0},
	{Sprite: 0},
	{CoinImage: 0},
	{CoinDisplay: 0},
	{BuyBtnFirst1: 0},
	{BuyBtnFirst2: 0},
	{BuyBtnFirst3: 0},
	{BuyBtnFirst4: 0},
	{BuyBtnFirst5: 0},
	{BuyBtnFirst6: 0},
	{ShopBtnMenu: 0},
	{ShopBtnPlay: 0},
	{BuyBtnFirst7: 0},
	{BuyBtnFirst8: 0},
	{BuyBtnFirst9: 0},
	{BuyBtnFirst10: 0},
	{BuyBtnFirst11: 0},
	{PaymentBG: 0},
	{BundleOfCoin: 0},
	{HomeBTN: 0},
	{CoinAmount: 0},
	{RealBirr: 0},
	{shopeTitle: 0},
	{ContinueBtn: 0},
	{RestartBtn: 0},
	{CloseBtn: 0},
	{CloseBtn2: 0},
	{ShopBoard: 0},
	{GameOVerBoard: 0},
	{ScoreBoardEn: 0},
	{BestScoreBoarden: 0},
	{ShopBoardMini: 0},
	{Sprite2: 0},
	{Sprite3: 0},
	{Sprite4: 0},
	{Sprite5: 0},
	{Sprite6: 0},
	{Sprite7: 0},
	{Sprite8: 0},
	{FBox: 0},
	{PUi: 0},
	{BGS: 0},
	{HUi: 0},
	{IsMute: 0},
	{TrueEnd: 0},
	{Funcheck: 0},
	{SuccessTEXT: 0},
	{IsSucccessfulPurches: 0},
	{s: 0},
	{ang: 0},
	{dL1: 0},
	{dL2: 0},
	{startX: 0},
	{startY: 0},
	{endX: 0},
	{endY: 0},
	{dir: 0},
	{extUID: 0},
	{extFrame: 0},
	{uidNear: 0},
	{double: 0},
	{uidNext: 0},
	{uidMarker: 0},
	{First: 0},
	{uidBox: 0},
	{uid: 0},
	{value: 0},
	{m: 0},
	{h: 0},
	{UID: 0},
	{possible: 0},
	{count: 0},
	{bx: 0},
	{by: 0},
	{bf: 0},
	{Score: 0},
	{BestScore: 0},
	{CurrentHieghstScore: 0},
	{KEYBestScore: 0},
	{TimerIncreasePerStack: 0},
	{TimeBought: 0},
	{TouchY: 0},
	{TouchX: 0},
	{Dim: 0},
	{ofsX: 0},
	{ofsY: 0},
	{StepTime: 0},
	{TIMECheck: 0},
	{KeyCoin: 0},
	{Coin: 0},
	{Amount1: 0},
	{Amount2: 0},
	{Amount3: 0},
	{Amount4: 0},
	{Amount5: 0},
	{Amount6: 0},
	{ChosenAmount: 0},
	{DecreaseNumberOfCoin: 0},
	{ScreenWidthValue: 0},
	{ScreenHeightValue: 0}
];

self.InstanceType = {
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	txtBest: class extends self.ITextInstance {},
	btnPlay: class extends self.ISpriteInstance {},
	character: class extends self.ISpriteInstance {},
	logo: class extends self.ISpriteInstance {},
	BoardBest: class extends self.ISpriteInstance {},
	BG1: class extends self.ISpriteInstance {},
	Box: class extends self.ISpriteInstance {},
	BoxNumber: class extends self.ITextInstance {},
	Tilemap: class extends self.ITilemapInstance {},
	Marker: class extends self.ISpriteInstance {},
	Syncer: class extends self.ISpriteInstance {},
	SuccsTXT: class extends self.ITextInstance {},
	TimeAdded: class extends self.ITextInstance {},
	btnPause: class extends self.ISpriteInstance {},
	btnReplay: class extends self.ISpriteInstance {},
	btnResume: class extends self.ISpriteInstance {},
	txtHelp: class extends self.ITextInstance {},
	txtScore: class extends self.ITextInstance {},
	logo2: class extends self.ISpriteInstance {},
	BG2: class extends self.ISpriteInstance {},
	score: class extends self.ISpriteInstance {},
	Timer: class extends self.ISpriteInstance {},
	txtTimer: class extends self.ITextInstance {},
	Label: class extends self.ITextInstance {},
	btnHome: class extends self.ISpriteInstance {},
	GoHomeBtn: class extends self.ISpriteInstance {},
	MusicBtn: class extends self.ISpriteInstance {},
	ExsitBtn: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	boy: class extends self.ISpriteInstance {},
	DBG: class extends self.ITextInstance {},
	soBad: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	CoinImage: class extends self.ISpriteInstance {},
	CoinDisplay: class extends self.ITextInstance {},
	BuyBtnFirst1: class extends self.ISpriteInstance {},
	BuyBtnFirst2: class extends self.ISpriteInstance {},
	BuyBtnFirst3: class extends self.ISpriteInstance {},
	BuyBtnFirst4: class extends self.ISpriteInstance {},
	BuyBtnFirst5: class extends self.ISpriteInstance {},
	BuyBtnFirst6: class extends self.ISpriteInstance {},
	ShopBtnMenu: class extends self.ISpriteInstance {},
	ShopBtnPlay: class extends self.ISpriteInstance {},
	BuyBtnFirst7: class extends self.ISpriteInstance {},
	BuyBtnFirst8: class extends self.ISpriteInstance {},
	BuyBtnFirst9: class extends self.ISpriteInstance {},
	BuyBtnFirst10: class extends self.ISpriteInstance {},
	BuyBtnFirst11: class extends self.ISpriteInstance {},
	PaymentBG: class extends self.ISpriteInstance {},
	BundleOfCoin: class extends self.ISpriteInstance {},
	HomeBTN: class extends self.ISpriteInstance {},
	CoinAmount: class extends self.ITextInstance {},
	RealBirr: class extends self.ITextInstance {},
	shopeTitle: class extends self.ITextInstance {},
	ContinueBtn: class extends self.ISpriteInstance {},
	RestartBtn: class extends self.ISpriteInstance {},
	CloseBtn: class extends self.ISpriteInstance {},
	CloseBtn2: class extends self.ISpriteInstance {},
	ShopBoard: class extends self.ISpriteInstance {},
	GameOVerBoard: class extends self.ISpriteInstance {},
	ScoreBoardEn: class extends self.ISpriteInstance {},
	BestScoreBoarden: class extends self.ISpriteInstance {},
	ShopBoardMini: class extends self.ISpriteInstance {},
	Sprite2: class extends self.ISpriteInstance {},
	Sprite3: class extends self.ISpriteInstance {},
	Sprite4: class extends self.ISpriteInstance {},
	Sprite5: class extends self.ISpriteInstance {},
	Sprite6: class extends self.ISpriteInstance {},
	Sprite7: class extends self.ISpriteInstance {},
	Sprite8: class extends self.ISpriteInstance {},
	FBox: class extends self.ISpriteInstance {},
	PUi: class extends self.ISpriteInstance {},
	BGS: class extends self.ISpriteInstance {},
	HUi: class extends self.ISpriteInstance {}
}