const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Behaviors.Timer,
		C3.Plugins.Particles,
		C3.Plugins.Text,
		C3.Behaviors.Flash,
		C3.Plugins.Gritsenko_Spine,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Pin,
		C3.Plugins.Browser,
		C3.Plugins.DrawingCanvas,
		C3.Plugins.Touch,
		C3.Plugins.Audio,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.Sin,
		C3.Plugins.TiledBg,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetScale,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Text.Acts.SetOpacity,
		C3.Behaviors.Pin.Acts.PinByImagePoint,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Exps.LayerNumber,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.System.Acts.SetBoolVar,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareOpacity,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Behaviors.Timer.Acts.StartTimer,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.JavaScriptInEvents.Gameplay_Event17_Act6,
		C3.Plugins.Browser.Acts.ConsoleLog,
		C3.Behaviors.Timer.Cnds.OnTimer,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Touch.Cnds.OnNthTouchStart,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Touch.Cnds.HasNthTouch,
		C3.Plugins.Sprite.Acts.SetTowardPosition,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.TiledBg.Acts.MoveToTop,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Acts.SetCollisions,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.Sprite.Acts.ZMoveToObject,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.Particles.Acts.SetRate,
		C3.Plugins.Particles.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.SetEffectParam,
		C3.Plugins.DrawingCanvas.Acts.PasteObject,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.Gritsenko_Spine.Cnds.IsSkeletonLoaded,
		C3.Plugins.Gritsenko_Spine.Acts.SetWidth,
		C3.Plugins.Gritsenko_Spine.Exps.TextureWidth,
		C3.Plugins.Gritsenko_Spine.Acts.SetHeight,
		C3.Plugins.Gritsenko_Spine.Exps.TextureHeight,
		C3.Plugins.Gritsenko_Spine.Cnds.OnAnimationFinished,
		C3.Plugins.Gritsenko_Spine.Acts.SetAnimation,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Touch.Cnds.OnTapGestureObject,
		C3.JavaScriptInEvents["Title-E_Event13_Act1"],
		C3.JavaScriptInEvents["Title-E_Event13_Act2"],
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.Audio.Acts.StopAll,
		C3.Plugins.TiledBg.Acts.SetOpacity
	];
};
self.C3_JsPropNameTable = [
	{Tween: 0},
	{Blade: 0},
	{BladeSmoother: 0},
	{Timer: 0},
	{GameManager: 0},
	{VectorX: 0},
	{VectorY: 0},
	{RotationSpeed: 0},
	{Luminosity: 0},
	{HalfObject: 0},
	{Life: 0},
	{Object: 0},
	{Orange: 0},
	{SmokeParticle: 0},
	{Watermelon: 0},
	{Title_bgs: 0},
	{Home_btn: 0},
	{Home_btn2: 0},
	{InstructionsText: 0},
	{Flash: 0},
	{SliceText: 0},
	{Grass_spine: 0},
	{Cur_Score: 0},
	{Best: 0},
	{Score_Fruit: 0},
	{High_Sco: 0},
	{Pin: 0},
	{Fail_high_Src: 0},
	{Fail_Score: 0},
	{Ready: 0},
	{Ready_Go: 0},
	{Browser: 0},
	{DrawingCanvas: 0},
	{Touch: 0},
	{Audio: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Sine: 0},
	{Title_play: 0},
	{Replay_btn: 0},
	{Menu_btn: 0},
	{Title_Spine: 0},
	{Fail_panel: 0},
	{Fail_Panel_back: 0},
	{Opacity: 0},
	{Lang_btn: 0},
	{Best_txt: 0},
	{Correct_mess: 0},
	{Slice_Correct: 0},
	{Tick: 0},
	{Two: 0},
	{Bomb_Two: 0},
	{Wrong_Two: 0},
	{Dont_Slice: 0},
	{Cross: 0},
	{Exsit_Button: 0},
	{Tap_conti: 0},
	{Highliht_Fade: 0},
	{Sound: 0},
	{Eng_btn: 0},
	{Spa_btn: 0},
	{Tur_btn: 0},
	{Rus_btn: 0},
	{Por_btn: 0},
	{Lang_Dark: 0},
	{Bags: 0},
	{play_btn2: 0},
	{Background: 0},
	{Fade: 0},
	{FireParticles: 0},
	{Apple: 0},
	{Lemon: 0},
	{Sprite: 0},
	{Ui_Sound: 0},
	{Fruit_decide_count: 0},
	{Lang_Stop: 0},
	{Total_Score: 0},
	{High_Score: 0},
	{Cout_val: 0},
	{Time_Set_1: 0},
	{Fail: 0},
	{Loose_count: 0},
	{FirstInteraction: 0},
	{DOUBLESPAWNRATE: 0},
	{BOMBSPAWNRATE: 0},
	{SCREENHORIZONTALMARGIN: 0},
	{RotationDirection: 0},
	{AllowPlayerToCut: 0},
	{PreviousX: 0},
	{PreviousY: 0},
	{RandomForce: 0},
	{Score: 0},
	{GameIsOver: 0},
	{Direction: 0},
	{CurrentValue: 0},
	{TargetValue: 0},
	{Speed: 0},
	{Lang_Layout: 0},
	{Lang_Layout2: 0},
	{Lang_Sel_count: 0},
	{Onstart: 0},
	{Ad_mute: 0},
	{Ad_time: 0},
	{Tap_Count: 0},
	{Tap_Time: 0}
];

self.InstanceType = {
	Blade: class extends self.ISpriteInstance {},
	BladeSmoother: class extends self.ISpriteInstance {},
	GameManager: class extends self.ISpriteInstance {},
	HalfObject: class extends self.ISpriteInstance {},
	Life: class extends self.ISpriteInstance {},
	Object: class extends self.ISpriteInstance {},
	Orange: class extends self.IParticlesInstance {},
	SmokeParticle: class extends self.IParticlesInstance {},
	Watermelon: class extends self.IParticlesInstance {},
	Title_bgs: class extends self.ISpriteInstance {},
	Home_btn: class extends self.ISpriteInstance {},
	Home_btn2: class extends self.ISpriteInstance {},
	InstructionsText: class extends self.ITextInstance {},
	SliceText: class extends self.ITextInstance {},
	Grass_spine: class extends self.IWorldInstance {},
	Cur_Score: class extends self.ISpriteFontInstance {},
	Best: class extends self.ISpriteFontInstance {},
	Score_Fruit: class extends self.ISpriteInstance {},
	High_Sco: class extends self.ISpriteFontInstance {},
	Fail_high_Src: class extends self.ISpriteFontInstance {},
	Fail_Score: class extends self.ISpriteFontInstance {},
	Ready: class extends self.ISpriteFontInstance {},
	Ready_Go: class extends self.ISpriteInstance {},
	Browser: class extends self.IInstance {},
	DrawingCanvas: class extends self.IDrawingCanvasInstance {},
	Touch: class extends self.IInstance {},
	Audio: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Title_play: class extends self.ISpriteInstance {},
	Replay_btn: class extends self.ISpriteInstance {},
	Menu_btn: class extends self.ISpriteInstance {},
	Title_Spine: class extends self.IWorldInstance {},
	Fail_panel: class extends self.ISpriteInstance {},
	Fail_Panel_back: class extends self.ISpriteInstance {},
	Opacity: class extends self.ISpriteInstance {},
	Lang_btn: class extends self.ISpriteInstance {},
	Best_txt: class extends self.ISpriteInstance {},
	Correct_mess: class extends self.ISpriteInstance {},
	Slice_Correct: class extends self.ISpriteInstance {},
	Tick: class extends self.ISpriteInstance {},
	Two: class extends self.ISpriteInstance {},
	Bomb_Two: class extends self.ISpriteInstance {},
	Wrong_Two: class extends self.ISpriteInstance {},
	Dont_Slice: class extends self.ISpriteInstance {},
	Cross: class extends self.ISpriteInstance {},
	Exsit_Button: class extends self.ISpriteInstance {},
	Tap_conti: class extends self.ISpriteInstance {},
	Highliht_Fade: class extends self.ITiledBackgroundInstance {},
	Sound: class extends self.ISpriteInstance {},
	Eng_btn: class extends self.ISpriteInstance {},
	Spa_btn: class extends self.ISpriteInstance {},
	Tur_btn: class extends self.ISpriteInstance {},
	Rus_btn: class extends self.ISpriteInstance {},
	Por_btn: class extends self.ISpriteInstance {},
	Lang_Dark: class extends self.ISpriteInstance {},
	Bags: class extends self.ISpriteInstance {},
	play_btn2: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Fade: class extends self.ITiledBackgroundInstance {},
	FireParticles: class extends self.IParticlesInstance {},
	Apple: class extends self.IParticlesInstance {},
	Lemon: class extends self.IParticlesInstance {},
	Sprite: class extends self.ISpriteInstance {},
	Ui_Sound: class extends self.ISpriteInstance {}
}