const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Arr,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Behaviors.wrap,
		C3.Behaviors.Bullet,
		C3.Behaviors.Pin,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Flash,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.Arr.Acts.SetXY,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Behaviors.Bullet.Acts.SetSpeed,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.random,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.MoveToBottom,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Keyboard.Cnds.IsKeyDown,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Behaviors.Flash.Acts.Flash,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.System.Exps.viewportheight,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Global_events_Event16_Act3,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.JavaScriptInEvents.Global_events_Event59_Act4,
		C3.JavaScriptInEvents.Global_events_Event59_Act5,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunLight: 0},
	{FramePaused: 0},
	{TextPaused: 0},
	{FrameInfo: 0},
	{TextGameInfo: 0},
	{Fade: 0},
	{TextTapToPlay: 0},
	{TextGameOver: 0},
	{TextGameResults: 0},
	{TextTimeOver: 0},
	{FrameTime: 0},
	{FrameFruits: 0},
	{FrameLives: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{TouchArea: 0},
	{SnakeLogo: 0},
	{FruitsMenu: 0},
	{BlastMenu: 0},
	{FruitsInfo: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{BodyPosition: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Plants: 0},
	{Blasts: 0},
	{Fruits: 0},
	{SpawnNumber: 0},
	{Body: 0},
	{Wrap: 0},
	{Bullet: 0},
	{Snake: 0},
	{Pin: 0},
	{FruitDetector: 0},
	{SnakeCollision: 0},
	{LastScoreFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{LoadingFont: 0},
	{ID: 0},
	{InfoFont: 0},
	{GameOverFont: 0},
	{BtnExit: 0},
	{BtnFacebook: 0},
	{BtnFullscreen: 0},
	{BtnPlay: 0},
	{BtnInfo: 0},
	{BtnMenu: 0},
	{BtnMoreGames: 0},
	{Button_Music: 0},
	{BtnPause: 0},
	{BtnReload: 0},
	{BtnReturn: 0},
	{Button_Sound: 0},
	{BtnStart: 0},
	{BtnTwitter: 0},
	{BtnGo: 0},
	{BtnRestart: 0},
	{BtnLeft: 0},
	{BtnRight: 0},
	{Buttons: 0},
	{TextFonts: 0},
	{Flash: 0},
	{SnakeBody: 0},
	{Lives: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{LastScore: 0},
	{BestScore: 0},
	{SnakeSpeed: 0},
	{CountSeconds: 0},
	{Pause: 0},
	{Fullscreen: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	FrameInfo: class extends self.ISpriteInstance {},
	TextGameInfo: class extends self.ISpriteInstance {},
	TextTapToPlay: class extends self.ISpriteInstance {},
	TextGameOver: class extends self.ISpriteInstance {},
	TextGameResults: class extends self.ISpriteInstance {},
	TextTimeOver: class extends self.ISpriteInstance {},
	FrameTime: class extends self.ISpriteInstance {},
	FrameFruits: class extends self.ISpriteInstance {},
	FrameLives: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	TouchArea: class extends self.ISpriteInstance {},
	SnakeLogo: class extends self.ISpriteInstance {},
	FruitsMenu: class extends self.ISpriteInstance {},
	BlastMenu: class extends self.ISpriteInstance {},
	FruitsInfo: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	BodyPosition: class extends self.IArrayInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Plants: class extends self.ISpriteInstance {},
	Blasts: class extends self.ISpriteInstance {},
	Fruits: class extends self.ISpriteInstance {},
	Body: class extends self.ISpriteInstance {},
	Snake: class extends self.ISpriteInstance {},
	FruitDetector: class extends self.ISpriteInstance {},
	SnakeCollision: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	InfoFont: class extends self.ISpriteFontInstance {},
	GameOverFont: class extends self.ISpriteFontInstance {},
	BtnExit: class extends self.ISpriteInstance {},
	BtnFacebook: class extends self.ISpriteInstance {},
	BtnFullscreen: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMenu: class extends self.ISpriteInstance {},
	BtnMoreGames: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	BtnPause: class extends self.ISpriteInstance {},
	BtnReload: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	BtnStart: class extends self.ISpriteInstance {},
	BtnTwitter: class extends self.ISpriteInstance {},
	BtnGo: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnLeft: class extends self.ISpriteInstance {},
	BtnRight: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	TextFonts: class extends self.ISpriteInstance {},
	SnakeBody: class extends self.ISpriteInstance {}
}