const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.Dictionary,
		C3.Plugins.LocalStorage,
		C3.Behaviors.Bullet,
		C3.Plugins.NinePatch,
		C3.Plugins.Spritefont2,
		C3.Behaviors.Fade,
		C3.Behaviors.Sin,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Dictionary.Acts.Clear,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.int,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.NinePatch.Acts.SetSize,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.Repeat,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.NinePatch.Acts.SetPos,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.NinePatch.Exps.Height,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Behaviors.Sin.Cnds.IsEnabled,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Mouse.Cnds.OnObjectClicked,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Cnds.While,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Dictionary.Exps.KeyCount,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Dictionary.Cnds.HasKey,
		C3.Plugins.Dictionary.Acts.AddKey,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Cnds.CompareWidth,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Sprite.Acts.MoveAtAngle,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.System.Exps.dt,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Behaviors.Fade.Acts.RestartFade,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Menuevent_Event9_Act4,
		C3.JavaScriptInEvents.Menuevent_Event9_Act5,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunRays: 0},
	{FramePaused: 0},
	{GuiLevel: 0},
	{GuiMatch: 0},
	{Name: 0},
	{GuiFrame: 0},
	{GuiScore: 0},
	{GuiTime: 0},
	{GuiTurns: 0},
	{Background: 0},
	{Background_Mask: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{CardNumber: 0},
	{CardRandom: 0},
	{LocalStorage: 0},
	{ID: 0},
	{Active: 0},
	{Touched: 0},
	{Number: 0},
	{Effect: 0},
	{Size: 0},
	{State: 0},
	{Speed: 0},
	{Bullet: 0},
	{Card: 0},
	{CardMatched: 0},
	{CardShadow: 0},
	{Card_Deck: 0},
	{MatchFont: 0},
	{HighScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{LoadingFont: 0},
	{GameScoreFont: 0},
	{OrientationFont: 0},
	{TurnsFont: 0},
	{LevelFont: 0},
	{Fade: 0},
	{TextFont: 0},
	{ButtonExit: 0},
	{ButtonFacebook: 0},
	{ButtonFullscreen: 0},
	{ButtonPlay: 0},
	{ButtonGooglePlus: 0},
	{ButtonMenu: 0},
	{ButtonMusic: 0},
	{ButtonPause: 0},
	{ButtonReload: 0},
	{ButtonReturn: 0},
	{ButtonSound: 0},
	{ButtonStart: 0},
	{ButtonTwitter: 0},
	{ButtonRestart: 0},
	{Game_Icon: 0},
	{Sine: 0},
	{Game_Logo: 0},
	{Small_Logo: 0},
	{Text_Time_Over: 0},
	{Text_Paused: 0},
	{Text_Tap_To_Play: 0},
	{Text_Game_Score: 0},
	{Text_Level_Completed: 0},
	{Text_Game_Completed: 0},
	{Touch_Area: 0},
	{Collision_Card_Deck: 0},
	{Buttons: 0},
	{Texts: 0},
	{CardsMatched: 0},
	{Game_Status: 0},
	{Mouse_Control: 0},
	{Level: 0},
	{Max_Levels: 0},
	{Card_ID: 0},
	{Cards: 0},
	{Card_Rows: 0},
	{Card_Columns: 0},
	{Card_Space_Between: 0},
	{Card_Width: 0},
	{Card_Height: 0},
	{Card_Turns: 0},
	{Card_Number: 0},
	{Card_Random: 0},
	{Card_Matched: 0},
	{Card_Touched: 0},
	{Margin_Top: 0},
	{Margin_Left: 0},
	{Match: 0},
	{Card_First: 0},
	{Card_Second: 0},
	{Score: 0},
	{Seconds: 0},
	{Minutes: 0},
	{High_Score: 0},
	{Count_Score: 0},
	{Count_Seconds: 0},
	{CurrentTableauCard: 0},
	{CurrentColumn: 0},
	{CurrentRow: 0},
	{Music: 0},
	{Sound: 0},
	{Fullscreen: 0},
	{GAME_NAME: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunRays: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	GuiLevel: class extends self.ISpriteInstance {},
	GuiMatch: class extends self.ISpriteInstance {},
	GuiFrame: class extends self.ISpriteInstance {},
	GuiScore: class extends self.ISpriteInstance {},
	GuiTime: class extends self.ISpriteInstance {},
	GuiTurns: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	Background_Mask: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	CardNumber: class extends self.IDictionaryInstance {},
	CardRandom: class extends self.IDictionaryInstance {},
	LocalStorage: class extends self.IInstance {},
	Card: class extends self.ISpriteInstance {},
	CardMatched: class extends self.ISpriteInstance {},
	CardShadow: class extends self.ISpriteInstance {},
	Card_Deck: class extends self.IWorldInstance {},
	MatchFont: class extends self.ISpriteFontInstance {},
	HighScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	GameScoreFont: class extends self.ISpriteFontInstance {},
	OrientationFont: class extends self.ISpriteFontInstance {},
	TurnsFont: class extends self.ISpriteFontInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonFacebook: class extends self.ISpriteInstance {},
	ButtonFullscreen: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonGooglePlus: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	ButtonMusic: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonReload: class extends self.ISpriteInstance {},
	ButtonReturn: class extends self.ISpriteInstance {},
	ButtonSound: class extends self.ISpriteInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	ButtonTwitter: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	Game_Icon: class extends self.ISpriteInstance {},
	Game_Logo: class extends self.ISpriteInstance {},
	Small_Logo: class extends self.ISpriteInstance {},
	Text_Time_Over: class extends self.ISpriteInstance {},
	Text_Paused: class extends self.ISpriteInstance {},
	Text_Tap_To_Play: class extends self.ISpriteInstance {},
	Text_Game_Score: class extends self.ISpriteInstance {},
	Text_Level_Completed: class extends self.ISpriteInstance {},
	Text_Game_Completed: class extends self.ISpriteInstance {},
	Touch_Area: class extends self.ISpriteInstance {},
	Collision_Card_Deck: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	CardsMatched: class extends self.ISpriteInstance {}
}