const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.PlatformInfo,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Game_events_Event11_Act2,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Sprite.Cnds.OnCreated,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.System.Exps.choose,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.SetMirrored,
		C3.Plugins.Sprite.Cnds.OnAnimFinished,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetLeft,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.Sprite.Exps.LayerNumber,
		C3.Plugins.PlatformInfo.Exps.SafeAreaInsetTop,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewportmidx,
		C3.Plugins.System.Exps.viewportmidy,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.System.Exps.viewportwidth,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.JavaScriptInEvents.Global_events_Event5_Act3,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.Sprite.Cnds.CompareY,
		C3.Plugins.Audio.Acts.Stop,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.JavaScriptInEvents.Global_events_Event59_Act3,
		C3.JavaScriptInEvents.Global_events_Event60_Act2,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Acts.Signal
	];
};
self.C3_JsPropNameTable = [
	{BtnMenu: 0},
	{BtnInfo: 0},
	{BtnMoreGames: 0},
	{BtnMusic: 0},
	{BtnPlay: 0},
	{BtnRestart: 0},
	{BtnReturn: 0},
	{BtnSound: 0},
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunLight: 0},
	{BtnClose: 0},
	{Sine: 0},
	{GameOver: 0},
	{Fade: 0},
	{Score: 0},
	{Background: 0},
	{GameLogo: 0},
	{EggsMenu: 0},
	{Audio: 0},
	{Browser: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{PlatformInfo: 0},
	{Loading: 0},
	{LoadingText: 0},
	{GameIcon: 0},
	{ID: 0},
	{SpawnPoint: 0},
	{Duck: 0},
	{Bullet_Hole: 0},
	{Collision: 0},
	{Eggs: 0},
	{Explosion: 0},
	{LastScoreFont: 0},
	{BulletsFont: 0},
	{BestScoreFont: 0},
	{ScoreFont: 0},
	{TimeFont: 0},
	{CurtainBack: 0},
	{CurtainTop: 0},
	{ButtonsSound: 0},
	{Bullets: 0},
	{Seconds: 0},
	{LastScore: 0},
	{BestScore: 0},
	{DuckSpeed: 0},
	{DuckSpawnTime: 0},
	{Music: 0},
	{Sound: 0},
	{Fullscreen: 0}
];

self.InstanceType = {
	BtnMenu: class extends self.ISpriteInstance {},
	BtnInfo: class extends self.ISpriteInstance {},
	BtnMoreGames: class extends self.ISpriteInstance {},
	BtnMusic: class extends self.ISpriteInstance {},
	BtnPlay: class extends self.ISpriteInstance {},
	BtnRestart: class extends self.ISpriteInstance {},
	BtnReturn: class extends self.ISpriteInstance {},
	BtnSound: class extends self.ISpriteInstance {},
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunLight: class extends self.ISpriteInstance {},
	BtnClose: class extends self.ISpriteInstance {},
	GameOver: class extends self.ISpriteInstance {},
	Score: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	EggsMenu: class extends self.ISpriteInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	PlatformInfo: class extends self.IInstance {},
	Loading: class extends self.ISpriteInstance {},
	LoadingText: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	SpawnPoint: class extends self.ISpriteInstance {},
	Duck: class extends self.ISpriteInstance {},
	Bullet_Hole: class extends self.ISpriteInstance {},
	Collision: class extends self.ISpriteInstance {},
	Eggs: class extends self.ISpriteInstance {},
	Explosion: class extends self.ISpriteInstance {},
	LastScoreFont: class extends self.ISpriteFontInstance {},
	BulletsFont: class extends self.ISpriteFontInstance {},
	BestScoreFont: class extends self.ISpriteFontInstance {},
	ScoreFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	CurtainBack: class extends self.ISpriteInstance {},
	CurtainTop: class extends self.ISpriteInstance {},
	ButtonsSound: class extends self.ISpriteInstance {}
}