const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Rotate,
		C3.Behaviors.Sin,
		C3.Behaviors.Fade,
		C3.Plugins.TiledBg,
		C3.Plugins.Audio,
		C3.Plugins.Browser,
		C3.Plugins.Keyboard,
		C3.Plugins.Mouse,
		C3.Plugins.Touch,
		C3.Plugins.LocalStorage,
		C3.Plugins.Spritefont2,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Acts.Spawn,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.Sprite.Acts.MoveToTop,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.System.Acts.SetGroupActive,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Cnds.CompareFrame,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Sprite.Cnds.CompareInstanceVar,
		C3.Plugins.Sprite.Acts.SetAnimFrame,
		C3.Plugins.Sprite.Exps.AnimationFrame,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.System.Cnds.CompareVar,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.viewportright,
		C3.Plugins.System.Exps.viewporttop,
		C3.Plugins.Spritefont2.Acts.SetPos,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Sprite.Acts.SetPosToObject,
		C3.Plugins.System.Cnds.Every,
		C3.Plugins.System.Acts.SubVar,
		C3.Plugins.System.Acts.AddVar,
		C3.Plugins.Audio.Acts.Play,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.Spritefont2.Acts.SetVisible,
		C3.Plugins.Sprite.Acts.SetVisible,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.Compare,
		C3.Plugins.Sprite.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Cnds.TriggerOnce,
		C3.Plugins.System.Acts.SetLayerOpacity,
		C3.Plugins.System.Acts.SetLayerScale,
		C3.Plugins.System.Exps.layeropacity,
		C3.Plugins.System.Exps.layerscale,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.System.Exps.projectname,
		C3.JavaScriptInEvents.Gameevent_Event616_Act5,
		C3.Plugins.System.Acts.WaitForSignal,
		C3.Plugins.System.Acts.GoToLayout,
		C3.JavaScriptInEvents.Gameevent_Event617_Act4,
		C3.JavaScriptInEvents.Gameevent_Event618_Act4,
		C3.JavaScriptInEvents.Gameevent_Event619_Act4,
		C3.Plugins.Sprite.Cnds.OnDestroyed,
		C3.Plugins.Sprite.Acts.SetY,
		C3.Plugins.TiledBg.Acts.SetHeight,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Exps.viewportleft,
		C3.Plugins.System.Exps.viewportbottom,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Cnds.OnCollision,
		C3.Plugins.TiledBg.Cnds.CompareHeight,
		C3.Plugins.TiledBg.Acts.SetY,
		C3.Plugins.TiledBg.Exps.Height,
		C3.Plugins.TiledBg.Cnds.CompareX,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetX,
		C3.Plugins.Mouse.Cnds.IsOverObject,
		C3.Behaviors.Sin.Acts.SetEnabled,
		C3.Plugins.Sprite.Cnds.CompareAnimSpeed,
		C3.Plugins.TiledBg.Acts.SetVisible,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.Keyboard.Cnds.OnAnyKey,
		C3.Plugins.Audio.Acts.Preload,
		C3.Plugins.System.Exps.loadingprogress,
		C3.Plugins.Spritefont2.Cnds.IsBoolInstanceVarSet,
		C3.Plugins.System.Cnds.OnLoadFinished,
		C3.Plugins.Spritefont2.Acts.SetBoolInstanceVar,
		C3.Plugins.System.Acts.SetTimescale,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.LocalStorage.Cnds.IsProcessingGets,
		C3.Plugins.Audio.Acts.SetVolume,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.RestartLayout,
		C3.Plugins.Browser.Acts.RequestFullScreen,
		C3.Plugins.Browser.Acts.CancelFullScreen,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Mouse.Cnds.IsButtonDown,
		C3.Plugins.Mouse.Acts.SetCursorSprite,
		C3.Plugins.System.Exps.windowwidth,
		C3.Plugins.System.Exps.windowheight,
		C3.Plugins.System.Acts.SetLayerVisible,
		C3.Plugins.System.Cnds.LayerCmpOpacity,
		C3.Plugins.System.Acts.Signal,
		C3.Plugins.Sprite.Acts.StartAnim,
		C3.JavaScriptInEvents.Menuevent_Event15_Act4,
		C3.JavaScriptInEvents.Menuevent_Event15_Act5,
		C3.Plugins.Spritefont2.Acts.SetPosToObject,
		C3.Plugins.Sprite.Cnds.IsAnimPlaying,
		C3.Plugins.Spritefont2.Cnds.CompareInstanceVar,
		C3.Plugins.Spritefont2.Acts.SetInstanceVar,
		C3.Plugins.Browser.Acts.GoToURLWindow
	];
};
self.C3_JsPropNameTable = [
	{Cursor: 0},
	{CursorHover: 0},
	{Rotate: 0},
	{SunRays: 0},
	{FramePaused: 0},
	{LevelCompleteFrame: 0},
	{LevelStars: 0},
	{Stars: 0},
	{FrameTop: 0},
	{ID: 0},
	{Closed: 0},
	{Background: 0},
	{Sine: 0},
	{GameLogo: 0},
	{GameIcon: 0},
	{Water: 0},
	{Plumber: 0},
	{Size: 0},
	{Bubble_0: 0},
	{Fade: 0},
	{Bubble_1: 0},
	{Bubble_2: 0},
	{WaterBackground: 0},
	{Audio: 0},
	{Browser: 0},
	{Keyboard: 0},
	{Mouse: 0},
	{Touch: 0},
	{LocalStorage: 0},
	{Active: 0},
	{Connected: 0},
	{Pipes: 0},
	{GateValve: 0},
	{Opened: 0},
	{GateValveHandwheel: 0},
	{Manometer: 0},
	{ManometerArrow: 0},
	{ManometerPipe: 0},
	{LongPipe: 0},
	{WaterPipe: 0},
	{WaterPipeBackground: 0},
	{PipeWater: 0},
	{Stub: 0},
	{Pipe: 0},
	{Nipple: 0},
	{LevelsFont: 0},
	{TextFont: 0},
	{TimeFont: 0},
	{LoadingFont: 0},
	{OrientationFont: 0},
	{LevelFont: 0},
	{ButtonExit: 0},
	{ButtonFacebook: 0},
	{ButtonFullscreen: 0},
	{ButtonPlay: 0},
	{ButtonGooglePlus: 0},
	{ButtonMenu: 0},
	{ButtonMoreGames: 0},
	{Button_Music: 0},
	{ButtonPause: 0},
	{ButtonReload: 0},
	{ButtonReturn: 0},
	{Button_Sound: 0},
	{ButtonStart: 0},
	{ButtonTwitter: 0},
	{ButtonRestart: 0},
	{ButtonNext: 0},
	{ButtonMenuBig: 0},
	{ButtonLevel: 0},
	{ButtonLeft: 0},
	{ButtonRight: 0},
	{TextPaused: 0},
	{TextGameScore: 0},
	{PipesShadow: 0},
	{ManometerShadow: 0},
	{ManometerPipeShadow: 0},
	{GateValveShadow: 0},
	{GateValveHandwheelShadow: 0},
	{LongPipeShadow: 0},
	{WaterPipeShadow: 0},
	{StubShadow: 0},
	{PipeShadow: 0},
	{NippleShadow: 0},
	{Buttons: 0},
	{Texts: 0},
	{HideObjects: 0},
	{PipeAngle_01: 0},
	{PipeAngle_02: 0},
	{PipeAngle_03: 0},
	{PipeAngle_04: 0},
	{PipeAngle_05: 0},
	{PipeAngle_06: 0},
	{PipeAngle_07: 0},
	{PipeAngle_08: 0},
	{PipeAngle_09: 0},
	{PipeAngle_10: 0},
	{PipeAngle_11: 0},
	{PipeAngle_12: 0},
	{PipeAngle_13: 0},
	{PipeAngle_14: 0},
	{PipeAngle_15: 0},
	{PipeAngle_16: 0},
	{PipeAngle_17: 0},
	{PipeAngle_18: 0},
	{PipeAngle_19: 0},
	{PipeAngle_20: 0},
	{PipeAngle_21: 0},
	{PipeAngle_22: 0},
	{PipeAngle_23: 0},
	{PipeAngle_24: 0},
	{PipeAngle_25: 0},
	{PipeAngle_26: 0},
	{PipeAngle_27: 0},
	{PipeAngle_28: 0},
	{PipeAngle_29: 0},
	{PipeAngle_30: 0},
	{PipeAngle_31: 0},
	{PipeAngle_32: 0},
	{PipeAngle_33: 0},
	{PipeAngle_34: 0},
	{PipeAngle_35: 0},
	{PipeAngle_36: 0},
	{PipeAngle_37: 0},
	{PipeAngle_38: 0},
	{PipeAngle_39: 0},
	{PipeAngle_40: 0},
	{PipeAngle_41: 0},
	{PipeAngle_42: 0},
	{PipeAngle_43: 0},
	{PipeAngle_44: 0},
	{PipeAngle_45: 0},
	{MaxLevels: 0},
	{Level: 0},
	{MaxConnected: 0},
	{Pressure: 0},
	{Seconds: 0},
	{Pause: 0},
	{Minutes: 0},
	{ShadowX: 0},
	{ShadowY: 0},
	{Sound: 0},
	{Sound_Status: 0},
	{Music: 0},
	{Music_Status: 0},
	{Fullscreen: 0},
	{LevelsPage: 0},
	{LevelStars_1: 0},
	{LevelStars_2: 0},
	{LevelStars_3: 0},
	{LevelStars_4: 0},
	{LevelStars_5: 0},
	{LevelStars_6: 0},
	{LevelStars_7: 0},
	{LevelStars_8: 0},
	{LevelStars_9: 0},
	{LevelStars_10: 0},
	{LevelStars_11: 0},
	{LevelStars_12: 0},
	{LevelStars_13: 0},
	{LevelStars_14: 0},
	{LevelStars_15: 0},
	{LevelStars_16: 0},
	{LevelStars_17: 0},
	{LevelStars_18: 0},
	{LevelStars_19: 0},
	{LevelStars_20: 0},
	{LevelStars_21: 0},
	{LevelStars_22: 0},
	{LevelStars_23: 0},
	{LevelStars_24: 0},
	{LevelStars_25: 0},
	{LevelStars_26: 0},
	{LevelStars_27: 0},
	{LevelStars_28: 0},
	{LevelStars_29: 0},
	{LevelStars_30: 0},
	{GAME_NAME: 0},
	{DESCRIPTION: 0},
	{REDIRECT_URL: 0},
	{IMAGE: 0}
];

self.InstanceType = {
	Cursor: class extends self.ISpriteInstance {},
	CursorHover: class extends self.ISpriteInstance {},
	SunRays: class extends self.ISpriteInstance {},
	FramePaused: class extends self.ISpriteInstance {},
	LevelCompleteFrame: class extends self.ISpriteInstance {},
	LevelStars: class extends self.ISpriteInstance {},
	Stars: class extends self.ISpriteInstance {},
	FrameTop: class extends self.ISpriteInstance {},
	Closed: class extends self.ISpriteInstance {},
	Background: class extends self.ISpriteInstance {},
	GameLogo: class extends self.ISpriteInstance {},
	GameIcon: class extends self.ISpriteInstance {},
	Water: class extends self.ISpriteInstance {},
	Plumber: class extends self.ISpriteInstance {},
	Bubble_0: class extends self.ISpriteInstance {},
	Bubble_1: class extends self.ISpriteInstance {},
	Bubble_2: class extends self.ISpriteInstance {},
	WaterBackground: class extends self.ITiledBackgroundInstance {},
	Audio: class extends self.IInstance {},
	Browser: class extends self.IInstance {},
	Keyboard: class extends self.IInstance {},
	Mouse: class extends self.IInstance {},
	Touch: class extends self.IInstance {},
	LocalStorage: class extends self.IInstance {},
	Pipes: class extends self.ISpriteInstance {},
	GateValve: class extends self.ISpriteInstance {},
	GateValveHandwheel: class extends self.ISpriteInstance {},
	Manometer: class extends self.ISpriteInstance {},
	ManometerArrow: class extends self.ISpriteInstance {},
	ManometerPipe: class extends self.ISpriteInstance {},
	LongPipe: class extends self.ISpriteInstance {},
	WaterPipe: class extends self.ISpriteInstance {},
	WaterPipeBackground: class extends self.ISpriteInstance {},
	PipeWater: class extends self.ITiledBackgroundInstance {},
	Stub: class extends self.ISpriteInstance {},
	Pipe: class extends self.ISpriteInstance {},
	Nipple: class extends self.ISpriteInstance {},
	LevelsFont: class extends self.ISpriteFontInstance {},
	TextFont: class extends self.ISpriteFontInstance {},
	TimeFont: class extends self.ISpriteFontInstance {},
	LoadingFont: class extends self.ISpriteFontInstance {},
	OrientationFont: class extends self.ISpriteFontInstance {},
	LevelFont: class extends self.ISpriteFontInstance {},
	ButtonExit: class extends self.ISpriteInstance {},
	ButtonFacebook: class extends self.ISpriteInstance {},
	ButtonFullscreen: class extends self.ISpriteInstance {},
	ButtonPlay: class extends self.ISpriteInstance {},
	ButtonGooglePlus: class extends self.ISpriteInstance {},
	ButtonMenu: class extends self.ISpriteInstance {},
	ButtonMoreGames: class extends self.ISpriteInstance {},
	Button_Music: class extends self.ISpriteInstance {},
	ButtonPause: class extends self.ISpriteInstance {},
	ButtonReload: class extends self.ISpriteInstance {},
	ButtonReturn: class extends self.ISpriteInstance {},
	Button_Sound: class extends self.ISpriteInstance {},
	ButtonStart: class extends self.ISpriteInstance {},
	ButtonTwitter: class extends self.ISpriteInstance {},
	ButtonRestart: class extends self.ISpriteInstance {},
	ButtonNext: class extends self.ISpriteInstance {},
	ButtonMenuBig: class extends self.ISpriteInstance {},
	ButtonLevel: class extends self.ISpriteInstance {},
	ButtonLeft: class extends self.ISpriteInstance {},
	ButtonRight: class extends self.ISpriteInstance {},
	TextPaused: class extends self.ISpriteInstance {},
	TextGameScore: class extends self.ISpriteInstance {},
	PipesShadow: class extends self.ISpriteInstance {},
	ManometerShadow: class extends self.ISpriteInstance {},
	ManometerPipeShadow: class extends self.ISpriteInstance {},
	GateValveShadow: class extends self.ISpriteInstance {},
	GateValveHandwheelShadow: class extends self.ISpriteInstance {},
	LongPipeShadow: class extends self.ISpriteInstance {},
	WaterPipeShadow: class extends self.ISpriteInstance {},
	StubShadow: class extends self.ISpriteInstance {},
	PipeShadow: class extends self.ISpriteInstance {},
	NippleShadow: class extends self.ISpriteInstance {},
	Buttons: class extends self.ISpriteInstance {},
	Texts: class extends self.ISpriteInstance {},
	HideObjects: class extends self.ISpriteInstance {}
}